spring.application.name=restaurant

# 5601 for kibana
spring.elasticsearch.uris=http://localhost:9200

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/restaurant-review